# Generated by Django 5.1.3 on 2024-11-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(blank=True, choices=[('WORKSHOP', 'Workshop'), ('SEMINAR', 'Seminar'), ('TRAINING', 'Training')], max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='url_link',
            field=models.URLField(blank=True),
        ),
    ]
